apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:latest
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 22
          env:
            GITLAB_OMNIBUS_CONFIG: |
              external_url 'http://gitlab.example.com'
              nginx['listen_port'] = 80
              nginx['listen_https'] = false
              # Otras configuraciones según sea necesario
          volumeMounts:
            - name: gitlab-data
              mountPath: /var/opt/gitlab
            - name: gitlab-logs
              mountPath: /var/log/gitlab
            - name: gitlab-config
              mountPath: /etc/gitlab
      volumes:
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-data
        - name: gitlab-logs
          persistentVolumeClaim:
            claimName: gitlab-logs
        - name: gitlab-config
          persistentVolumeClaim:
            claimName: gitlab-config

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Puedes elegir el puerto que desees
    - port: 443
      targetPort: 443
      nodePort: 30443  # Puedes elegir el puerto que desees
  selector:
    app: gitlab
