apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv
spec:
  capacity:
    storage: 10Gi  # Debe coincidir con el PVC
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/gitlab  # Cambia esta ruta según tu entorno
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:latest
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 22
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://gitlab.example.com'
                gitlab_rails['gitlab_shell_ssh_port'] = 22
          volumeMounts:
            - name: gitlab-storage
              mountPath: /var/opt/gitlab
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: gitlab-storage
          persistentVolumeClaim:
            claimName: gitlab-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080  # Puerto HTTP
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443  # Puerto HTTPS
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 30022  # Puerto SSH válido
  selector:
    app: gitlab
